openapi: 3.0.0
info:
  title: ScrapIn API
  version: 1.0.0
servers:
- url: https://api.scrapin.io
security:
- apiKey: []
tags:
- name: Person
- name: Company
paths:
  '/enrichment':
    get:
      tags:
      - Person
      operationId: PersonSearch
      summary: Person Search
      description: This operation allows you to find someone from first name, last name, company domain or email. It returns data profile and company information as the response. This operation consume 1 credit.
      parameters:
      - name: firstName
        in: query
        schema:
          type: string
        description: This optional parameter is a string. It represents the first name to query.
      - name: lastName
        in: query
        schema:
          type: string
        description: This optional parameter is a string. It represents the last name to query.
      - name: companyDomain
        in: query
        schema:
          type: string
        description: This optional parameter is a string. It represents the company domain/URL to query
      - name: email
        in: query
        schema:
          type: string
        description: This required parameter is a string. It represents the email to query.
      responses:
        200:
          description: 'The endpoint returns information about the person found and its company. There are two possible success responses for the operation. <br />1. Query Successful but no data found. <br />2. Query Successful with data found.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonSearch'
              examples:
                ProfileFound:
                  $ref: '#/components/examples/ProfileFound'
                ProfileNotFound:
                  $ref: '#/components/examples/ProfileNotFound'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseSchema'
              examples:
                NoApiKey:
                  $ref: '#/components/examples/NoApiKey'
                MissingEmail:
                  $ref: '#/components/examples/MissingEmail'
                InvalidEmail:
                  $ref: '#/components/examples/InvalidEmail'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseSchema'
              examples:
                InvalidApiKey:
                  $ref: '#/components/examples/InvalidApiKey'
              
        402:
          description: Insufficient Account Balance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseSchema'
              examples:
                PaymentRequired:
                  $ref: '#/components/examples/PaymentRequired'
        404:
          description: Page Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseSchema'
              examples:
                PageNotFound:
                  $ref: '#/components/examples/PageNotFound'
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseSchema'
              examples:
                ServerError:
                  $ref: '#/components/examples/ServerError'
  '/enrichment/profile':
    get:
      tags:
      - Person
      operationId: ExtractPersonDataProfile
      summary: Extract Person Data Profile
      description: This operation allows you to extract data from a Person Linkedin URL. It returns profile data and current company data of the person as the response. This operation consume 1 credit.
      parameters:
      - name: linkedinUrl
        in: query
        schema:
          type: string
        description: "This required parameter is a string. It represents the Linkedin URL of the person with this format: https://www.linkedin.com/in/xxxxxxxxxxxxx/."
        required: true
      responses:
        200:
          description: 'The endpoint returns information about the Linkedin URL owner and its company.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExtractPersonDataProfile'
              examples:
                ProfileFound:
                  $ref: '#/components/examples/PersonProfileExtracted'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseSchema'
              examples:
                NoApiKey:
                  $ref: '#/components/examples/NoApiKey'
                MissingEmail:
                  $ref: '#/components/examples/MissingEmail'
                InvalidEmail:
                  $ref: '#/components/examples/InvalidEmail'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseSchema'
              examples:
                InvalidApiKey:
                  $ref: '#/components/examples/InvalidApiKey'

        402:
          description: Insufficient Account Balance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseSchema'
              examples:
                PaymentRequired:
                  $ref: '#/components/examples/PaymentRequired'
        404:
          description: Page Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseSchema'
              examples:
                PageNotFound:
                  $ref: '#/components/examples/PageNotFound'
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseSchema'
              examples:
                ServerError:
                  $ref: '#/components/examples/ServerError'
  '/enrichment/company/domain':
    get:
      tags:
      - Company
      operationId: CompanySearch
      summary: Company Search
      description: This operation allows you to find a company from its domain name. It returns company information as the response. This operation consume 1 credit.
      parameters:
      - name: domain
        in: query
        schema:
          type: string
        description: "This required parameter is a string. It represents the domain name of the company to query."
        required: true
      responses:
        200:
          description: 'The endpoint returns information about the company. There are two possible success responses for the operation. <br />1. Query Successful but no data found. <Br />2. Query Successful with data found.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompanySearch'
              examples:
                CompanyFound:
                  $ref: '#/components/examples/CompanyFound'
                CompanyNotFound:
                  $ref: '#/components/examples/CompanyNotFound'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseSchema'
              examples:
                NoApiKey:
                  $ref: '#/components/examples/NoApiKey'
                MissingEmail:
                  $ref: '#/components/examples/MissingEmail'
                InvalidEmail:
                  $ref: '#/components/examples/InvalidEmail'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseSchema'
              examples:
                InvalidApiKey:
                  $ref: '#/components/examples/InvalidApiKey'
              
        402:
          description: Insufficient Account Balance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseSchema'
              examples:
                PaymentRequired:
                  $ref: '#/components/examples/PaymentRequired'
        404:
          description: Page Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseSchema'
              examples:
                PageNotFound:
                  $ref: '#/components/examples/PageNotFound'
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseSchema'
              examples:
                ServerError:
                  $ref: '#/components/examples/ServerError'
  '/enrichment/company':
    get:
      tags:
      - Company
      operationId: ExtractCompanyDataProfile
      summary: Extract Company Data Profile
      description: This operation allows you to extract data from a Company Linkedin URL. It returns company data as the response. This operation consume 1 credit.
      parameters:
      - name: linkedInUrl
        in: query
        schema:
          type: string
        description: "This required parameter is a string. It represents the Linkedin URL of the person with this format: https://www.linkedin.com/company/xxxxxxxxxx/."
        required: true
      responses:
        200:
          description: 'The endpoint returns information about the Linkedin URL owner and its company.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExtractCompanyDataProfile'
              examples:
                CompanyFound:
                  $ref: '#/components/examples/CompanyProfileExtracted'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseSchema'
              examples:
                NoApiKey:
                  $ref: '#/components/examples/NoApiKey'
                MissingEmail:
                  $ref: '#/components/examples/MissingEmail'
                InvalidEmail:
                  $ref: '#/components/examples/InvalidEmail'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseSchema'
              examples:
                InvalidApiKey:
                  $ref: '#/components/examples/InvalidApiKey'

        402:
          description: Insufficient Account Balance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseSchema'
              examples:
                PaymentRequired:
                  $ref: '#/components/examples/PaymentRequired'
        404:
          description: Page Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseSchema'
              examples:
                PageNotFound:
                  $ref: '#/components/examples/PageNotFound'
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseSchema'
              examples:
                ServerError:
                  $ref: '#/components/examples/ServerError'
components:
  schemas:
    PersonSearch:
      type: object
      properties:
        success:
          type: boolean
          description: Indicates success or failure of api request.
        email:
          type: string
          description: Represents the email of the person account that was queried
        emailType:
          type: string
          description: Represents the type of account.
        person:
          oneOf:
          - $ref: '#/components/schemas/Person'
          - type: boolean
            enum:
            - false
        company:
          oneOf:
          - $ref: '#/components/schemas/Company'
          - type: boolean
            enum:
            - false
        credits_left:
          type: integer
          description: Represents the usable credits available for the user account after this query.
        rate_limit_left:
          type: integer
          description: Represents the usable daily request limit available for the user account after this query.
    Person:
      type: object
      properties:
        connectionCount:
          type: number
        creationDate:
          type: object
          properties:
            month:
              type: number
            year:
              type: number
        firstName:
          type: string
        followerCount:
          type: number
        headline:
          type: string
        languages:
          type: array
          items:
            type: string
        lastName:
          type: string
        linkedInIdentifier:
          type: string
        linkedInUrl:
          type: string
        location:
          type: string
        photoUrl:
          type: string
        positions:
          type: object
          properties:
            positionHistory:
              type: array
              items:
                type: object
                properties:
                  companyLocation:
                    type: string
                  companyLogo:
                    type: string
                  companyName:
                    type: string
                  description:
                    type: string
                  linkedInUrl:
                    type: string
                  startEndDate:
                    type: object
                    properties:
                      start:
                        type: object
                        properties:
                          month:
                            type: number
                          year:
                            type: number
                      end:
                        type: object
                        properties:
                          month:
                            type: number
                          year:
                            type: number
                  title:
                    type: string
                  contractType:
                    type: string
            positionsCount:
              type: number
        publicIdentifier:
          type: string
        schools:
          type: object
          properties:
            educationHistory:
              type: array
              items:
                type: object
                properties:
                  degreeName:
                    type: string
                  description:
                    type: string
                  fieldOfStudy:
                    type: string
                  linkedInUrl:
                    type: string
                  schoolLogo:
                    type: string
                  schoolName:
                    type: string
                  startEndDate:
                    type: object
                    properties:
                      end:
                        type: object
                        properties:
                          year:
                            type: number
                      start:
                        type: object
                        properties:
                          year:
                            type: number
            educationsCount:
              type: number
        skills:
          type: array
          items:
            type: string
    ExtractPersonDataProfile:
      type: object
      properties:
        success:
          type: boolean
          description: Indicates success or failure of api request.
        credits_left:
          type: integer
          description: The usable credits available for the user account after this query.
        rate_limit_left:
          type: integer
          description: The usable daily request limit available for the user account after this query.
        person:
          oneOf:
          - $ref: '#/components/schemas/Person'
          - type: boolean
            enum:
            - false
        company:
          oneOf:
          - $ref: '#/components/schemas/Company'
          - type: boolean
            enum:
            - false
    Company:
      type: object
      properties:
        description:
          type: string
        employeeCount:
          type: number
        headquarter:
          type: object
          properties:
            city:
              type: string
            country:
              type: string
            geographicArea:
              type: string
            postalCode:
              type: string
        industry:
          type: string
        linkedInId:
          type: string
        linkedInUrl:
          type: string
        name:
          type: string
        specialities:
          type: array
          items:
            type: string
        tagline:
          type: string
        universalName:
          type: string
        websiteUrl:
          type: string
    CompanySearch:
      type: object
      properties:
        success:
          type: boolean
          description: Indicates success or failure of api request.
        credits_left:
          type: integer
          description: Represents the usable credits available for the user account after this query.
        rate_limit_left:
          type: integer
          description: Represents the usable daily request limit available for the user account after this query.
        company:
          oneOf:
          - $ref: '#/components/schemas/Company'
          - type: boolean
            enum:
            - false
    ExtractCompanyDataProfile:
      type: object
      properties:
        success:
          type: boolean
          description: Indicates success or failure of api request.
        credits_left:
          type: integer
          description: Represents the usable credits available for the user account after this query.
        rate_limit_left:
          type: integer
          description: Represents the usable daily request limit available for the user account after this query.
        company:
          oneOf:
          - $ref: '#/components/schemas/Company'
          - type: boolean
            enum:
            - false
    ErrorResponseSchema:
      type: object
      properties:
        success:
          type: boolean
          enum:
          - false
        title:
          type: string
        msg:
          type: string

  examples:
    ProfileFound:
      summary: Profile Found
      value:
        success: true
        email: ilies@visum.run
        emailType: professional
        credits_left: 20602
        person:
          publicIdentifier: iliesgraffion-visum-find-stacks-of-anyone
          linkedInIdentifier: ACoAABeeBc4BdhwvD1RNk_40gtabNjwzUgvost0
          firstName: Ili√®s
          lastName: Graffion B.ü¶â
          headline: CTO @Visum | Data Hunter
          location: France
          photoUrl: https://media.licdn.com/dms/image/D4D03AQGINx51I2LHjA/profile-displayphoto-shrink_800_800/0/1633356200321?e=1695859200&v=beta&t=KqxxNeX7QSXUw8YKmR7uRDc19bBVgS2ctRrRisa1PC0
          creationDate:
            month: 1
            year: 2015
          followerCount: 5400
          connectionCount: 5148
          positions:
            positionsCount: 5
            positionHistory:
              - startEndDate:
                  start:
                    month: 12
                    year: 2020
                title: CEO
                description: Visum.run lets you know what tools, services and applications anyone is using from their email address.
                companyName: Visum
                companyLocation: Ville de Paris, √éle-de-France, France
                companyLogo: https://media.licdn.com/dms/image/C4E0BAQEbr48diDvnrw/company-logo_200_200/0/1674558570304?e=1698883200&v=beta&t=H5dvspy_TFn_g74R6JbuGOp3eUMNPNR3dFPJU0ugPZg
                linkedInUrl: https://www.linkedin.com/company/71234370/
              - startEndDate:
                  start:
                    month: 7
                    year: 2020
                contractType: Self-employed
                title: 'Co-founder '
                description: Repos Digital vous accompagne dans la suppression des donn√©es et la r√©siliation des contrats d'un d√©funt.
                companyName: 'Repos Digital '
                companyLocation: Ville de Paris, √éle-de-France, France
                companyLogo: https://media.licdn.com/dms/image/C4D0BAQGBtwCMV-deCA/company-logo_200_200/0/1625094869961?e=1698883200&v=beta&t=JEn-cCVXf2pZCzbrmxHYntSSneIG6xagEETP3cEToxM
                linkedInUrl: https://www.linkedin.com/company/65841732/
              - startEndDate:
                  start:
                    month: 8
                    year: 2017
                  end:
                    month: 7
                    year: 2020
                title: DevOps Engineer
                description: |-
                  Integration and development of tools on PaaS Cloud Foundry and OpenShift.
                  Implementation of a Development and Continuous Integration pipeline.
                companyName: Orange
                companyLocation: Orange Gardens - Ch√¢tillon
                companyLogo: https://media.licdn.com/dms/image/C4D0BAQEIG5RkDRNPvg/company-logo_200_200/0/1574431121488?e=1698883200&v=beta&t=v6BlehKgjUHd7vM8OIACs47Ety8_SHewfP1CfAXh-98
                linkedInUrl: https://www.linkedin.com/company/1110/
              - startEndDate:
                  start:
                    month: 12
                    year: 2017
                  end:
                    month: 2
                    year: 2018
                title: Graphic & Video Campaign Manager
                description: |-
                  I brought skills in graphics and video FX to Phore Blockchain. I'm also experienced in web design and development. I worked with the French and Belgian community and helped oversee the largest French discord community.

                  After winning the video contest of the young start-up, the members of their team quickly contacted me so that I realize various audiovisual achievements.

                  It is with almost 150,000 views on the last promotional video that I realized that the reputation of the project has increased sharply at the beginning of the year.
                companyName: Phore Blockchain
                companyLocation: Paris La D√©fense, √éle-de-France, France
                companyLogo: https://media.licdn.com/dms/image/C4E0BAQFcSihW9o0mXA/company-logo_200_200/0/1520369176944?e=1698883200&v=beta&t=hozOcQhhnZuA2jG8FtxV5q3ur_gZRJuprVQapwLh3iI
                linkedInUrl: https://www.linkedin.com/company/18353394/
              - startEndDate:
                  start:
                    month: 1
                    year: 2017
                  end:
                    month: 4
                    year: 2017
                title: Lead Software Engineer
                description: |-
                  It was with great pleasure and enthusiasm that I helped friends to start their startup.

                  It was in a start-up competition organized by Start in Saclay (https://startinsaclay.fr/) that we were selected to participate in a competition in the prestigious HEC establishment.
                  We finished our race at the final of the Pitch SEED EntrepreneurShip Summit 2017.

                  My missions at the start-up were:
                  ‚Ä¢ Supervise the technical aspects of the project
                  ‚Ä¢ Develop a demo of the smartphone application on Android
                  ‚Ä¢ Develop the website showcase of the application and the start-up
                companyName: Stapler
                companyLocation: R√©gion de Paris, France
                companyLogo: https://media.licdn.com/dms/image/C4E0BAQHygsJM2BlsWQ/company-logo_200_200/0/1519902766393?e=1698883200&v=beta&t=vHEz40JNm4ocu5p5BNhfMc_q0sHlDxKyMuZMTLUYUzU
                linkedInUrl: https://www.linkedin.com/company/18106104/
          schools:
            educationsCount: 3
            educationHistory:
              - startEndDate:
                  start:
                    year: 2017
                  end:
                    year: 2020
                schoolName: ESILV - Ecole Sup√©rieure d'Ing√©nieurs L√©onard de Vinci
                description: |-
                  The IBO Major trains general IT engineers, able to master all components of information processing. To meet the changing strategic needs of the company, the future engineer will be trained in information systems, database architecture, mobility and application development.

                  Computers, Big Data and Connected Objects.
                degreeName: Engineering degree, Computers, Big Data and Connected Objects
                fieldOfStudy: Engineering degree, Computers, Big Data and Connected Objects
                schoolLogo: https://media.licdn.com/dms/image/C560BAQF-voGLcZoK6w/company-logo_200_200/0/1642158124302?e=1698883200&v=beta&t=Nave9d9f8zyAgEmAB-i_Ncn1v3MnAsBW2EjiqohBsck
                linkedInUrl: https://www.linkedin.com/company/15142508/
              - startEndDate:
                  start:
                    year: 2018
                  end:
                    year: 2019
                schoolName: Shanghai Normal University
                degreeName: Summer School Program, Programme d'√©change international
                fieldOfStudy: Summer School Program, Programme d'√©change international
                schoolLogo: https://media.licdn.com/dms/image/C560BAQGhFlIwwrPy5Q/company-logo_200_200/0/1584115242490?e=1698883200&v=beta&t=xPM9J4HfzQ2GSFGp3m55fHRP-KCnPmCsLEdTpyZ-2Gc
                linkedInUrl: https://www.linkedin.com/company/15093901/
              - startEndDate:
                  start:
                    year: 2015
                  end:
                    year: 2016
                schoolName: Conservatoire National des Arts et M√©tiers
                description: This degree offers a professional training in the business of information systems engineering and decision making. Its purpose is to facilitate the professional insertion in IT fields in continuous growth.
                degreeName: ' Professional License Computer Systems and Database,  Analyst-Designer in Information and Decision System (ACSID)'
                fieldOfStudy: ' Professional License Computer Systems and Database,  Analyst-Designer in Information and Decision System (ACSID)'
                schoolLogo: https://media.licdn.com/dms/image/C4D0BAQGRQuv1v-KRxQ/company-logo_200_200/0/1604394648285?e=1698883200&v=beta&t=Vl3o5KIX8Rp2g-hFKnfy7ph9B3xgLSl-CoFY-fume2o
                linkedInUrl: https://www.linkedin.com/company/15091873/
          skills:
            - Reverse Contact
            - AngularJS
            - PHP
            - Java
            - JavaScript
            - SQL
            - HTML5
            - CSS
            - Git
            - API Google Maps
            - API Google Charts
            - Sourcetree
            - Oracle
            - UML
            - C++
            - Linux
            - MySQL
            - Bitbucket
            - Gestion machine SSH
            - Conception de syst√®mes
          languages:
            - Anglais
            - Arabe
            - Fran√ßais
          linkedInUrl: https://www.linkedin.com/in/iliesgraffion-visum-find-stacks-of-anyone/en
        company:
          websiteUrl: https://visum.run
          name: Visum
          employeeCount: 8
          description: |-
            In other words ‚Äúthe mister gadget‚Äù of Data enrichment.

            We specialize in hunting down all types of data for your business - with over 5 years of experience and already 3 enrichment tools created, we're dedicated to providing you with the most comprehensive and up-to-date data possible, no matter how complex or difficult it may be to get it.

            Trust us to be your data hunting experts and help you stay ahead of the competition.
          tagline: Data Hunter for companies
          specialities:
            - Lead Generation
            - Lead Qualification
            - Market Search
            - Competitor analysis
            - CRM enrichment
          headquarter:
            country: FR
            geographicArea: √éle-de-France
            city: Paris
            postalCode: '75013'
          industry: Computer Software
          universalName: visum-run
          linkedInUrl: https://www.linkedin.com/company/visum-run/
          linkedInId: '71234370'
    ProfileNotFound:
      summary: Profile Not Found
      value:
        success: true
        email: efzefhzefzef@live.fr
        emailType: personal
        credits_left: 140
        person: false
        company: false
    PersonProfileExtracted:
      summary: Person Profile Extracted
      value:
        success: true
        credits_left: 4337
        rate_limit_left: 19608
        person:
          publicIdentifier: julien-keraval-visum
          linkedInIdentifier: ACoAACJrg3QBOHYEx_zMaj2sF7IgUFOpF5VLkss
          firstName: Julien
          lastName: Keraval
          headline: COO @ Visum | Data Hunter
          location: Paris, √éle-de-France France
          photoUrl: https://media.licdn.com/dms/image/C4D03AQEN7W54z8qsHQ/profile-displayphoto-shrink_800_800/0/1633355607781?e=1701907200&v=beta&t=79-W0gvK6hm_TK3liARic0iUnTYY1F6qbF_vkQV-ZoI
          creationDate:
            year: 2017
          followerCount: 6197
          connectionCount: 5747
          emails: []
          phoneNumbers: []
          positions:
            positionsCount: 6
            positionHistory:
              - startEndDate:
                  start:
                    month: 12
                    year: 2020
                title: Co-founder & COO
                description: Visum collects all the data you need to help your sales & marketing team
                companyName: 'Visum '
                companyLocation: Ville de Paris, √éle-de-France, France
                companyLogo: https://media.licdn.com/dms/image/C4E0BAQEbr48diDvnrw/company-logo_200_200/0/1674558570304?e=1704326400&v=beta&t=qk9thQBKgXOkog_Ii-EZF1NxdbSuCvUkQE4-u_TUNsY
                linkedInUrl: https://www.linkedin.com/company/71234370/
              - startEndDate:
                  start:
                    month: 3
                    year: 2020
                title: Directeur marketing
                description: Repos Digital recherche et s√©curise les r√©seaux sociaux, bo√Ætes mails et messageries apr√®s d√©c√®s.
                companyName: 'Repos Digital '
                companyLocation: Paris Ouest La D√©fense
                companyLogo: https://media.licdn.com/dms/image/C4D0BAQGBtwCMV-deCA/company-logo_200_200/0/1625094869961?e=1704326400&v=beta&t=YBIB_x52MvVB1gx4wQxr-r7I7O8yHPRuVz-fonyKpQs
                linkedInUrl: https://www.linkedin.com/company/65841732/
              - startEndDate:
                  start:
                    month: 9
                    year: 2019
                  end:
                    month: 7
                    year: 2020
                title: Engineering Project Manager
                companyName: Safran
                companyLocation: V√©lizy-Villacoublay, √éle-de-France, France
                companyLogo: https://media.licdn.com/dms/image/C4D0BAQF12gJLvR-O3Q/company-logo_200_200/0/1519935017250?e=1704326400&v=beta&t=8L57xyEJPGaJ6CQhKq0i2mF5IsywCOZuUWGGNRPgeTk
                linkedInUrl: https://www.linkedin.com/company/521777/
              - startEndDate:
                  start:
                    month: 8
                    year: 2017
                  end:
                    month: 9
                    year: 2019
                title: Test Manager
                companyName: Safran
                companyLocation: V√©lizy-Villacoublay, √éle-de-France, France
                companyLogo: https://media.licdn.com/dms/image/C4D0BAQF12gJLvR-O3Q/company-logo_200_200/0/1519935017250?e=1704326400&v=beta&t=8L57xyEJPGaJ6CQhKq0i2mF5IsywCOZuUWGGNRPgeTk
                linkedInUrl: https://www.linkedin.com/company/521777/
              - startEndDate:
                  start:
                    month: 9
                    year: 2019
                  end:
                    month: 1
                    year: 2020
                contractType: Self-employed
                title: D√©veloppeur web / Webmarketing freelance
                description: |-
                  - Cr√©ation de maquettes
                  - D√©veloppement de site web
                  - Int√©gration de module de paiement (workflow e-commerce et/ou Marketplace)
                  - Int√©gration de module de livraison / exp√©dition
                  - Int√©gration de module de r√©servation
                  - Mise en production de site web / application web
                  - Configuration DNS
                  - Creation d‚Äôapplication mobile native Android + IOS et mise en ligne sur les stores (avec gestion du workflow de test)
                  - Configuration de serveur mail
                  - Configuration de serveur web (Apache et/ou Ngnix)
                  - Mise en place de funnel de conversion
                  - Int√©gration CRM
                  - Mise en place marketing automation
                  - Am√©lioration du r√©f√©rencement Web (SEO)
                  - Mise en place SEA (Search Engine Advertising)
                  - Cr√©ation et gestion de campagne de PUB sur les r√©seaux sociaux
                  - Cr√©ation et gestion de blog entreprise (content marketing) => Ecriture, diffusion, analyse
                  - Monitoring et maintenance de serveur web
                  - Evolution de site / application web existant
                  - Migration d‚Äôh√©bergeur web
                  - Conseil Marketing, Business, Informatique etc.
                  - Formation √† diff√©rent langage de d√©veloppement web (html5, css, JavaScript, PHP ‚Ä¶)
                  - Formation √† diff√©rent Framework de d√©veloppement web (Laravel, Vue.js, node.js, express.js, bootstrap, Vuetify‚Ä¶)
                  - Formation √† diff√©rent CMS (WordPress, WooCommerce ‚Ä¶)
                companyName: 'Malt '
                companyLocation: Ville de Paris, √éle-de-France, France
                companyLogo: https://media.licdn.com/dms/image/D4E0BAQE6sdo2FBxl2Q/company-logo_200_200/0/1689250164264?e=1704326400&v=beta&t=bwUHhylNGcXOipjwBMyFGzJKnx5Vl_l3-DUddjLcu8c
                linkedInUrl: https://www.linkedin.com/company/5285846/
              - startEndDate:
                  start:
                    month: 9
                    year: 2015
                  end:
                    month: 8
                    year: 2017
                title: Assistant chef d'exploitation
                companyName: GRDF
                companyLocation: Villeneuve-le-Roi, √éle-de-France, France
                companyLogo: https://media.licdn.com/dms/image/C4E0BAQFbrgye86-8pw/company-logo_200_200/0/1671574027730?e=1704326400&v=beta&t=GPrlvhxJCtiPI2PgOBLs-OOXEtbiRmWZdA5BClbHAdI
                linkedInUrl: https://www.linkedin.com/company/1037919/
          schools:
            educationsCount: 2
            educationHistory:
              - startEndDate:
                  start:
                    year: 2017
                  end:
                    year: 2020
                schoolName: ESILV - Ecole Sup√©rieure d'Ing√©nieurs L√©onard de Vinci
                description: |-
                  The IBO Major trains general IT engineers, able to master all components of information processing. To meet the changing strategic needs of the company, the future engineer will be trained in information systems, database architecture, mobility and application development.

                  Program Overview
                  Computers, Big Data and Connected Objects

                  ‚Ä¢ ADVANCED SOFTWARE DEVELOPMENT: Architecture & Programming, Advanced Data Structures and Algorithms, Software Development Process, Java EE & Frameworks; Mobile Application development, Web Application Architectures;
                  ‚Ä¢ DATABASES: Advanced Topics in NoSQL Databases, Advanced Database Management;
                  ‚Ä¢ BIG DATA: Machine Learning and Clustering;
                  ‚Ä¢ NETWORKS: Network Management & Security;
                  ‚Ä¢ INFORMATION SYSTEMS: Cloud computing & Datacenters, IT management, B.I. SAP;
                  ‚Ä¢ INFORMATION PROCESSING: Parallel computing, Multimedia Information Processing;
                  ‚Ä¢ EMBEDDED SYSTEMS: Embedded Systems.
                degreeName: Dipl√¥me d'ing√©nieur, Informatique, Big data et Objets connect√©s
                fieldOfStudy: Dipl√¥me d'ing√©nieur, Informatique, Big data et Objets connect√©s
                schoolLogo: https://media.licdn.com/dms/image/C560BAQF-voGLcZoK6w/company-logo_200_200/0/1642158124302?e=1704326400&v=beta&t=mSoLd4M_OiQ2zuzoycEcFaKV9-bjxMMpnw-PeIMRb6k
                linkedInUrl: https://www.linkedin.com/company/15142508/
              - schoolName: Pepite x Schoolab
                description: |-
                  P√©pite Start‚Äôup Ile-de-France a √©t√© cr√©√© par les P√âPITE franciliens et par P√©pite √éle-de-France, avec le le soutien de la R√©gion Ile-de-France, en collaboration avec le Schoolab. Il est con√ßu pour les √âtudiants-Entrepreneurs des P√âPITE franciliens.

                  C‚Äôest un programme d‚Äôaccompagnement early stage pendant lesquels vous travaillez √† 100 % √† sur votre projet de cr√©ation.

                  P√âPITE Start‚Äôup vous emm√®ne sur le terrain pour confronter votre id√©e au march√©, prototyper et tester votre produit pour qu‚Äôil devienne un business. Vous rencontrez des experts pour vous challenger et participez √† des ateliers pour monter en comp√©tences, le tout dans un espace de travail unique √† Station F.
                degreeName: Pepite Start'up IDF at Station F, Entrepreneuriat / √©tudes entrepreneuriales
                fieldOfStudy: Pepite Start'up IDF at Station F, Entrepreneuriat / √©tudes entrepreneuriales
                schoolLogo: null
                linkedInUrl: null
          skills:
            - Reverse Contact
            - D√©veloppement d‚ÄôAPI
            - Marketing num√©rique
            - Lean Startup
            - Gestion du changement
            - Testing
            - Optimisation des moteurs de recherche (SEO)
            - Marketing par moteur de recherche (SEM)
            - Marketing sur les m√©dias sociaux
            - Programmation
            - Tests de syst√®mes
            - HP Quality Center
            - JavaScript
            - HTML5
            - CSS
            - SAP
            - MongoDB
            - NoSQL
            - Python
            - SQL
          languages:
            - Anglais
            - Fran√ßais
        company:
          websiteUrl: https://visum.run
          name: Visum
          logo: https://media.licdn.com/dms/image/C4E0BAQEbr48diDvnrw/company-logo_200_200/0/1674558570304?e=1704326400&v=beta&t=qk9thQBKgXOkog_Ii-EZF1NxdbSuCvUkQE4-u_TUNsY
          employeeCount: 8
          description: |-
            In other words ‚Äúthe mister gadget‚Äù of Data enrichment.

            We specialize in hunting down all types of data for your business - with over 5 years of experience and already 3 enrichment tools created, we're dedicated to providing you with the most comprehensive and up-to-date data possible, no matter how complex or difficult it may be to get it.

            Trust us to be your data hunting experts and help you stay ahead of the competition.
          tagline: Data Hunter for companies
          specialities:
            - Lead Generation
            - Lead Qualification
            - Market Search
            - Competitor analysis
            - CRM enrichment
          headquarter:
            country: FR
            geographicArea: √éle-de-France
            city: Paris
            postalCode: '75013'
          industry: Technology, Information and Internet
          universalName: visum-run
          linkedinUrl: https://www.linkedin.com/company/visum-run/
          linkedinId: '71234370'
    CompanyFound:
      summary: Company Found
      value:
        success: true
        credits_left: 1773
        rate_limit_left: 19989
        company:
          linkedInUrl: https://www.linkedin.com/company/visum-run/
          name: Visum
          websiteUrl: https://visum.run
          logo: https://media.licdn.com/dms/image/C4E0BAQEbr48diDvnrw/company-logo_200_200/0/1674558570304?e=1705536000&v=beta&t=F9SV8wQpI8HVpJPUZSmiGAGpWHDo1kGTVOgc2wJwEsw
          description: |-
            In other words ‚Äúthe mister gadget‚Äù of Data enrichment.

            We specialize in hunting down all types of data for your business - with over 5 years of experience and already 3 enrichment tools created, we're dedicated to providing you with the most comprehensive and up-to-date data possible, no matter how complex or difficult it may be to get it.

            Trust us to be your data hunting experts and help you stay ahead of the competition.
          tagline: Data Hunter for companies
          specialities:
            - Lead Generation
            - Lead Qualification
            - Market Search
            - Competitor analysis
            - CRM enrichment
          headquarter:
            country: FR
            geographicArea: √éle-de-France
            city: Paris
            postalCode: '75013'
          industry: Technology, Information and Internet
          employeeCount: 8
          universalName: visum-run
          linkedInId: '71234370'
    CompanyNotFound:
      summary: Company Not Found
      value:
        success: true
        credits_left: 1773
        rate_limit_left: 19989
        company: false
    CompanyProfileExtracted:
      summary: Company Profile Extracted
      value:
        success: true
        credits_left: 1796
        rate_limit_left: 19999
        company:
          linkedInUrl: https://www.linkedin.com/company/visum-run/
          name: Visum
          websiteUrl: https://visum.run
          logo: https://media.licdn.com/dms/image/C4E0BAQEbr48diDvnrw/company-logo_200_200/0/1674558570304?e=1704326400&v=beta&t=qk9thQBKgXOkog_Ii-EZF1NxdbSuCvUkQE4-u_TUNsY
          description: |-
            In other words ‚Äúthe mister gadget‚Äù of Data enrichment.

            We specialize in hunting down all types of data for your business - with over 5 years of experience and already 3 enrichment tools created, we're dedicated to providing you with the most comprehensive and up-to-date data possible, no matter how complex or difficult it may be to get it.

            Trust us to be your data hunting experts and help you stay ahead of the competition.
          tagline: Data Hunter for companies
          specialities:
            - Lead Generation
            - Lead Qualification
            - Market Search
            - Competitor analysis
            - CRM enrichment
          headquarter:
            country: FR
            geographicArea: √éle-de-France
            city: Paris
            postalCode: '75013'
          industry: Technology, Information and Internet
          employeeCount: 8
          universalName: visum-run
          linkedInId: '71234370'
    NoApiKey:
      summary: No Api Key
      value:
        success: false
        title: An error has occurred üöí
        msg: The API Key is missing
    InvalidEmail:
      summary: Invalid Email
      value:
        success: false
        title: An error has occurred üöí
        msg: The email has the wrong format
    MissingEmail:
      summary: Missing Email
      value:
        success: false
        title: An error has occurred üöí
        msg: The email is missing
    InvalidApiKey:
      summary: Invalid Api Key
      value:
        success: false
        title: An error has occurred üöí
        msg: Unauthorized
    PaymentRequired:
      summary: Payment Required
      value:
        success: false
        title: You don't have enough credits on your account üí∞
        msg: You have to upgrade to continue
    PageNotFound:
      summary: Page Not Found
      value:
        success: false
        title: An error has occurred üöí
        msg: This LinkedIn Profile is not available or does not exist.
    ServerError:
      summary: Server Error
      value:
        success: false
        title: An error has occurred üöí
        msg: üö® Internal Server Error, you will not be credit debited.
  securitySchemes:
    apiKey:
      name: apikey
      in: query
      type: apiKey
      description: This required parameter is a string. It represents the APIKEY obtained from the developer dashboard.
